import express from 'express';
import { validateJWT, authorize } from '../middleware/auth.js';
import { sendEmail, sendBookingConfirmation, sendQuotation, sendPromo, listPromos } from '../controllers/emailController.js';
const router = express.Router();
router.use(validateJWT);
router.post('/email/send', authorize('admin', 'agent'), sendEmail);
router.post('/email/booking-confirmation', authorize('admin', 'agent'), sendBookingConfirmation);
router.post('/email/quotation', authorize('admin', 'agent'), sendQuotation);
router.post('/email/promo', authorize('admin'), sendPromo);
router.get('/email/promos', authorize('admin', 'agent'), listPromos);
export default router;
