#!/bin/sh
# entrypoint.sh — inject BACKEND_URL into config.js before starting Nginx

set -e

# Default backend URL if not provided
BACKEND_URL="${BACKEND_URL:-http://localhost:8081}"

echo ">>> Injecting API endpoint: ${BACKEND_URL}"

# Overwrite config.js with the runtime environment value
cat > /usr/share/nginx/html/js/config.js <<EOF
// config.js — auto-generated by entrypoint.sh at container startup
const Endpoint = "${BACKEND_URL}";
EOF

echo ">>> config.js written successfully"

# Dynamic PORT replacement for Nginx (Railway compatibility)
PORT="${PORT:-80}"
echo ">>> Configuring Nginx to listen on port: ${PORT}"
sed -i "s/listen 80;/listen ${PORT};/g" /etc/nginx/conf.d/default.conf

# Start Nginx in foreground
exec nginx -g 'daemon off;'
