#!/bin/sh
# entrypoint.sh — inject BACKEND_URL into config.js before starting Nginx

set -e

# Default backend URL if not provided
BACKEND_URL="${BACKEND_URL:-http://localhost:8081}"

echo ">>> Injecting API endpoint: ${BACKEND_URL}"

# Overwrite config.js with the runtime environment value
cat > /usr/share/nginx/html/js/config.js <<EOF
// config.js — auto-generated by entrypoint.sh at container startup
const Endpoint = "${BACKEND_URL}";
EOF

echo ">>> config.js written successfully"

# Start Nginx in foreground
exec nginx -g 'daemon off;'
