#!/bin/sh
# entrypoint.sh — inject BACKEND_URL into config.js before starting Nginx

set -e

# Default backend URL if not provided
BACKEND_URL="${BACKEND_URL:-https://gracious-trust-production-cc0c.up.railway.app}"

# Browsers block HTTPS pages from calling public HTTP APIs. Keep localhost
# unchanged for local development, but upgrade public Railway/custom domains.
case "$BACKEND_URL" in
  http://localhost*|http://127.0.0.1*|http://0.0.0.0*)
    ;;
  http://*)
    BACKEND_URL="https://${BACKEND_URL#http://}"
    ;;
esac

echo ">>> Injecting API endpoint: ${BACKEND_URL}"

# Overwrite config.js with the runtime environment value
mkdir -p /usr/share/nginx/html/production/js
cat > /usr/share/nginx/html/production/js/config.js <<EOF
// config.js — auto-generated by entrypoint.sh at container startup
const Endpoint = "${BACKEND_URL}";
EOF

echo ">>> config.js written successfully"

# Dynamic PORT replacement for Nginx (Railway compatibility)
PORT="${PORT:-80}"
echo ">>> Configuring Nginx to listen on port: ${PORT}"
sed -i "s/listen 80;/listen ${PORT};/g" /etc/nginx/conf.d/default.conf

# Start Nginx in foreground
exec nginx -g 'daemon off;'
